### ISSUE TITLE
Issues with `golang.org` packages

### ISSUE THREAD

**Issue by arekkas** [davecheney/graphpkg#11]
I have troubles running graphpkg with packages that depend on `golang.org`:

```
$ graphpkg github.com/ory-am/fosite
2016/09/07 08:58:49 cannot find package "golang_org/x/net/http2/hpack" in any of:
        C:\Go\src\golang_org\x\net\http2\hpack (from $GOROOT)
        D:\workspace\go\src\golang_org\x\net\http2\hpack (from $GOPATH)
```

I can confirm this on mac too, so it's not a windows issue

**Comment by davecheney** [comment]
If you've recently upgraded your go install, you may need to rebuild
graphpkg

**Comment by arekkas** [comment]
That didn't do it either (unless I messed up), I did `go get -u github.com/davecheney/graphpkg && go install github.com/davecheney/graphpkg`. I am on Go 1.7

**Comment by davecheney** [comment]
Use -v to check it did something.

**Comment by arekkas** [comment]
On mac it was a fresh install anyways, on windows I did (I am using git bash):

```
$ rm $GOPATH/bin/graphpkg.exe
$ go install -v github.com/davecheney/graphpkg
github.com/davecheney/graphpkg
```

**Comment by davecheney** [comment]
Ok, let me check out. There is some funkiness with the way the stb lib uses
internal packages which grqphviz doesn't understand

**Comment by arekkas** [comment]
Thanks for your immediate support, appreciated!

**Comment by davecheney** [comment]
I cannot reproduce this problem locally. If you're on windows, you probably have to set `%GOROOT%`, is it pointing to the right place ?

**Comment by arekkas** [comment]
Wow this is weird, because I get the problem both on windows and on mac, which I use regularly (every day) for go developing. Did you try it with the same package as I? `$GOROOT` and `$GOPATH` are both pointing at the right location on both systems.

**Comment by arekkas** [comment]
This is what the problem looks like on OSX:

```
$ graphpkg github.com/ory-am/fosite
2016/09/07 09:19:00 cannot find package "golang_org/x/net/route" in any of:
	/usr/local/go/src/golang_org/x/net/route (from $GOROOT)
	/Users/aeneas/workspaces/go/src/golang_org/x/net/route (from $GOPATH)
```

**Comment by arekkas** [comment]
I tried graphpkg on the package that wasn't found, and I get:

```
$ go get golang.org/x/net/route
$ graphpkg golang.org/x/net/route
2016/09/07 10:30:39 exec: "dot": executable file not found in $PATH
```

**Comment by davecheney** [comment]
Ok, now I'm getting somewhere, thanks for the repro

```

% graphpkg $(go list github.com/ory-am/fosite)

2016/09/07 18:32:43 cannot find package "golang_org/x/net/route" in any of:

        /Users/dfc/go/src/golang_org/x/net/route (from $GOROOT)

        /Users/dfc/src/golang_org/x/net/route (from $GOPATH)

```

**Comment by sbinet** [comment]
do you have vendor disabled by any chance?
notice the `golang_org/...` instead of `golang.org/...`. ie: a `_` instead of `.`.

**Comment by arekkas** [comment]
> do you have vendor disabled by any chance?

No, vendor is enabled. I am on Go 1.7.

> notice the golang_org/... instead of golang.org/.... ie: a _ instead of ..

Definitely linked to this and `exec: "dot": executable file not found in $PATH` from https://github.com/davecheney/graphpkg/issues/11#issuecomment-245212014

**Comment by davecheney** [comment]
FWIW, you should totally not be using this package and use https://github.com/hirokidaichi/goviz instead.
